### ISSUE TITLE
Container won't start. RTNETLINK Operation not permitted.

### ISSUE THREAD

**Issue by JRussell** [WeeJeWel/wg-easy#123]
Hello, hoping someone can help with this.

I have a VM running Ubuntu server LTS and using Portainer to manage my docker stuff.

My buddy also uses portainer and doesn't have any issues. We compared our compose files and they look the same.

When I start the compose file it gets stuck in a loop creating containers and the log shows an error

```
2021-11-16T16:47:51.276Z Server Listening on http://0.0.0.0:51821,
2021-11-16T16:47:51.278Z WireGuard Loading configuration...,
2021-11-16T16:47:51.280Z WireGuard Configuration loaded.,
2021-11-16T16:47:51.281Z WireGuard Saving config...,
2021-11-16T16:47:51.284Z WireGuard Config saved.,
$ wg-quick down wg0,
$ wg-quick up wg0,
Error: Command failed: wg-quick up wg0,
Warning: `/etc/wireguard/wg0.conf' is world accessible,
[#] ip link add wg0 type wireguard,
RTNETLINK answers: Operation not permitted,
Unable to access interface: Operation not permitted,
[#] ip link delete dev wg0,
Cannot find device "wg0",
,
    at ChildProcess.exithandler (child_process.js:383:12),
    at ChildProcess.emit (events.js:400:28),
    at maybeClose (internal/child_process.js:1058:16),
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {,
  killed: false,,
  code: 1,,
  signal: null,,
  cmd: 'wg-quick up wg0',
}
```

Here is my compose:
```
version: "3.8"
services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=redacted.com

      # Optional:
      - PASSWORD=redacted
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=192.168.86.x
      - WG_DEFAULT_DNS=192.168.84.1
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - /home/jrussell/wireguard:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

**Comment by WeeJeWel** [comment]
Sounds like your host's kernel doesn't support WireGuard.

**Comment by JRussell** [comment]
I'm running 20.04.3 LTS (GNU/Linux 5.4.0-90-generic x86_64)

My buddy that has it working is on 5.4.0-89

**Comment by JRussell** [comment]
Yup. The problem is that when Portainer is in a swarm it doesn't support the cap_add commands. I nuked Portainer, killed the swarm, redeployed Portainer normally and now it works.

**Comment by niem94** [comment]
I can confirm. This is related to #137 and is not a problem with `wg-easy` but most likely Portainer and missing support for capabilities.
