### ISSUE TITLE
WG_PATH does not get used in wg-quick command..

### ISSUE THREAD

**Issue by jdeath** [WeeJeWel/wg-easy#149]
I need to use the WG_PATH variable, as I want this to work with homeassistant, where I can set the volume.

When using WG_PATH, the config files save correctly, but the server does not use the path when starting wireguard, it defaults to /etc/wireguard , see below.

Also, would be great if the CSS could use relative paths.
:
wg-quick: `/etc/wireguard/wg0.conf' does not exist
    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:686:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'wg-quick up wg0'
}

**Comment by WeeJeWel** [comment]
Because this runs inside a Docker container, WG_PATH makes no sense. Simply mount `/etc/wireguard/` to wherever you want on your host.
