### ISSUE TITLE
Cannot startup WireGuard

### ISSUE THREAD

**Issue by ItzYanick** [WeeJeWel/wg-easy#15]
So I did the installation step by step but when I try to start it up using `docker-compose up` it just throws a error.

```
wg-easy    | 2021-05-26T17:23:40.717Z Server Listening on http://0.0.0.0:51821
wg-easy    | 2021-05-26T17:23:40.719Z WireGuard Loading configuration...
wg-easy    | $ wg genkey
wg-easy    | $ echo <propably secret ;)> | wg pubkey
wg-easy    | 2021-05-26T17:23:40.734Z WireGuard Configuration generated.
wg-easy    | 2021-05-26T17:23:40.735Z WireGuard Saving config...
wg-easy    | 2021-05-26T17:23:40.737Z WireGuard Config saved.
wg-easy    | $ wg-quick up wg0
wg-easy    | Error: Command failed: wg-quick up wg0
wg-easy    | Warning: '/etc/wireguard/wg0.conf' is world accessible
wg-easy    | [#] ip link add wg0 type wireguard
wg-easy    | RTNETLINK answers: Not supported
wg-easy    | Unable to access interface: Protocol not supported
wg-easy    | [#] ip link delete dev wg0
wg-easy    | Cannot find device "wg0"
wg-easy    | 
wg-easy    |     at ChildProcess.exithandler (child_process.js:319:12)
wg-easy    |     at ChildProcess.emit (events.js:376:20)
wg-easy    |     at maybeClose (internal/child_process.js:1055:16)
wg-easy    |     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
wg-easy    |   killed: false,
wg-easy    |   code: 1,
wg-easy    |   signal: null,
wg-easy    |   cmd: 'wg-quick up wg0'
wg-easy    | }
```

It seems like something is missing which should not be the case if it is in a Docker Container.

**Comment by WeeJeWel** [comment]
I think your host's kernel doesn't support WireGuard.

**Comment by ItzYanick** [comment]
I am setting it up in a LXC Container. I will have a look maybe I forgot something.

**Comment by ItzYanick** [comment]
Okay so I had to install wireguard-dkms on my Proxmox Host Machine. After that it was available for the LXC Container and the docker container inside of the LXC.
