### ISSUE TITLE
Auto restart ?

### ISSUE THREAD

**Issue by sam7oo** [WeeJeWel/wg-easy#17]
**how to fix it???**

$ wg-quick up wg0

Error: Command failed: wg-quick up wg0

[#] ip link add wg0 type wireguard

RTNETLINK answers: Operation not permitted

Unable to access interface: Protocol not supported

[#] ip link delete dev wg0

Cannot find device "wg0"

    at ChildProcess.exithandler (child_process.js:319:12)

    at ChildProcess.emit (events.js:376:20)

    at maybeClose (internal/child_process.js:1055:16)

    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {

  killed: false,

  code: 1,

  signal: null,

  cmd: 'wg-quick up wg0'

**Comment by tisyang** [comment]
Maybe your host linux kernel version < 5.6， you should upgrade your host system kernel.

**Comment by WeeJeWel** [comment]
Please make sure your host's kernel supports WireGuard.
