### ISSUE TITLE
Amazon Linux 2 - docker image doesn't run

### ISSUE THREAD

**Issue by junoteam** [WeeJeWel/wg-easy#205]
Docker version of wg-easy doesn't work on Amazon Linux 2

Run: 
```bash 
docker run -d \
  --name=wg-easy \
  -e WG_HOST=<ip> \
  -e PASSWORD=<password> \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  weejewel/wg-easy
```

Error: 
```bash 
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:63:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/lib/WireGuard.js:61:9
2022-02-17T13:28:40.263Z Server Listening on http://0.0.0.0:51821
2022-02-17T13:28:40.264Z WireGuard Loading configuration...
2022-02-17T13:28:40.265Z WireGuard Configuration loaded.
2022-02-17T13:28:40.265Z WireGuard Config saving...
2022-02-17T13:28:40.266Z WireGuard Config saved.
```

Wireguard is installed and running as expected standalone.

**Comment by WeeJeWel** [comment]
OK, well, fix it!

**Comment by junoteam** [comment]
@WeeJeWel Why closed the issue, if it's not solved yet
