### ISSUE TITLE
Various commands failing in Podman

### ISSUE THREAD

**Issue by buleherb** [WeeJeWel/wg-easy#27]
I wanted to try this in Podman as I don't use Docker. To create the container, I initially tried to use [podman-compose](https://github.com/containers/podman-compose) on the docker-compose.yml file. This resulted in error saying about the wg-easy pod being already created, so I decided to manually do create the pod and container now that I had the docker-compose command as a docker/podman create command.

I created a pod to hold the container:

`podman pod create --cgroup-manager=cgroupfs --name wg-easy_pod --share cgroup,uts,ipc`

I used the options '--cgroup-manager=cgroupfs' as I'm on Debian Bullseye and this is the only way to get Podman containers to run properly. I also used '--share cgroup,uts,ipc' so that I didn't have to open ports when creating the pod.

I then ran the command:

`podman create --name=wg-easy --pod=wg-easy_pod -l io.podman.compose.config-hash=123 -l io.podman.compose.project=wg-easy -l io.podman.compose.version=0.0.1 -l com.docker.compose.container-number=1 -l com.docker.compose.service=wg-easy -e WG_HOST=h-1.ddns.net --mount type=bind,source=/root/wg-easy/.,destination=/etc/wireguard --add-host wg-easy:127.0.0.1 --add-host wg-easy:127.0.0.1 --cgroup-manager=cgroupfs docker.io/weejewel/wg-easy`

I inserted '--cgroup-manager=cgroupfs' for the same reason as before, and made sure to enter my WG_HOST parameter.

This went fine, no errors in creating the container from the image. The container wouldn't start though. To investigate why, I looked at the logs of the wg-easy container using `podman logs wg-easy`. Below is the output:

2021-06-03T23:13:11.516Z Server Listening on http://0.0.0.0:51821
2021-06-03T23:13:11.520Z WireGuard Loading configuration...
$ wg genkey
$ echo QJYozOS5Y9kJ+y5ZG2a4Pq9gxBYLiM/gB7hU7hId0XM= | wg pubkey
2021-06-03T23:13:11.553Z WireGuard Configuration generated.
2021-06-03T23:13:11.554Z WireGuard Saving config...
2021-06-03T23:13:11.557Z WireGuard Config saved.
$ wg-quick up wg0
Error: Command failed: wg-quick up wg0
Warning: `/etc/wireguard/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
RTNETLINK answers: Operation not permitted
Unable to access interface: Operation not permitted
[#] ip link delete dev wg0
Cannot find device "wg0"
    at ChildProcess.exithandler (child_process.js:319:12)
    at ChildProcess.emit (events.js:376:20)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:376:20)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'wg-quick up wg0'
}

(I couldn't get the code-text format working for the above chunk)

I haven't had issues running Docker images in Podman, although of course was not expecting this to go 100% smoothly as it was my first time trying to use a docker-compose file with Podman. It would be amazing if this project could be compatible with Podman.

I'm running DietPi 7.2.3 (Debian Bullseye) on an RPi 4B 4GB. 

Podman version:
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.9
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/arm64

**Comment by buleherb** [comment]
Similar results if i simply try to create the container without putting it in a pod. Container exits with error, logs are as follows:

2021-06-03T23:45:17.955Z Server Listening on http://0.0.0.0:51821
2021-06-03T23:45:17.958Z WireGuard Loading configuration...
2021-06-03T23:45:17.962Z WireGuard Configuration loaded.
2021-06-03T23:45:17.962Z WireGuard Saving config...
2021-06-03T23:45:17.966Z WireGuard Config saved.
$ wg-quick up wg0
Error: Command failed: wg-quick up wg0
Warning: `/etc/wireguard/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
RTNETLINK answers: Operation not permitted
Unable to access interface: Operation not permitted
[#] ip link delete dev wg0
Cannot find device "wg0"
    at ChildProcess.exithandler (child_process.js:319:12)
    at ChildProcess.emit (events.js:376:20)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:376:20)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'wg-quick up wg0'
}

**Comment by WeeJeWel** [comment]
Not really an issue, closing this!
