### ISSUE TITLE
weejewel/wg-easy:5-nightly: Error: Command failed: wg-quick up wg0

### ISSUE THREAD

**Issue by zibous** [WeeJeWel/wg-easy#276]
**OS / System:**
```ni
Linux 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux
Client: Docker Engine - Community
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:17:38 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:15:44 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
**Docker install:**
```bash
# ----------------------------------------------
# sudo sh wg-easy.sh
# ----------------------------------------------
DOCKERIMAGE=weejewel/wg-easy
CONTAINERLABEL="wg-easy"
DOCKER_APPSDIR="/apps/"
APPSDATA="/docker/apps/${CONTAINERLABEL}"

echo "Create config for ${CONTAINERLABEL}: ${APPSDATA}"
mkdir -p ${APPSDATA}

echo "Install Docker container ${CONTAINERLABEL}"
docker run -d \
  --name=wg-easy \
  -e WG_HOST=********* \
  -e PASSWORD=******* \
  -v ${APPSDATA}:/etc/wireguard \
  -p 51825:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --sysctl="net.ipv6.conf.all.disable_ipv6=0" \
  --restart unless-stopped \
  weejewel/wg-easy:5-nightly
```

Container Log:
```
2022-06-07T07:35:18.238Z Server Listening on http://0.0.0.0:51821
2022-06-07T07:35:18.239Z WireGuard Loading configuration...
2022-06-07T07:35:18.241Z WireGuard Configuration loaded.
2022-06-07T07:35:18.241Z WireGuard Config saving...
2022-06-07T07:35:18.243Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: Command failed: wg-quick up wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.8.0.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
iptables v1.8.3 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
[#] ip link delete dev wg0

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  killed: false,
  code: 3,
  signal: null,
  cmd: 'wg-quick up wg0'
}
2022-06-07T07:36:14.437Z Server Listening on http://0.0.0.0:51821
2022-06-07T07:36:14.439Z WireGuard Loading configuration...
2022-06-07T07:36:14.441Z WireGuard Configuration loaded.
2022-06-07T07:36:14.441Z WireGuard Config saving...
2022-06-07T07:36:14.442Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: Command failed: wg-quick up wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.8.0.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
iptables v1.8.3 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
[#] ip link delete dev wg0
    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  killed: false,
  code: 3,
  signal: null,
  cmd: 'wg-quick up wg0'
}
```

How can I fix the error `wg-quick up wg0` ?

**Comment by WeeJeWel** [comment]
Upgrade your host's kernel.
