### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by fr0der1c** [WeeJeWel/wg-easy#290]
Following the README, I start the container with the following command:

```
docker run -d \
  --name=wg-easy \
  -e WG_HOST=xxxxxx \
  -e PASSWORD=xxxxxxx \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  weejewel/wg-easy
```

I got the following error:
```
docker logs -f 6b56126963dc21cdc515d6c758f1d949c55f203d36542b27e360ddbc556ae80a
2022-06-15T05:34:33.902Z Server Listening on http://0.0.0.0:51821
2022-06-15T05:34:33.903Z WireGuard Loading configuration...
2022-06-15T05:34:33.905Z WireGuard Configuration loaded.
2022-06-15T05:34:33.905Z WireGuard Config saving...
2022-06-15T05:34:33.906Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: Command failed: wg-quick up wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.8.0.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] iptables -t nat -A POSTROUTING -s 192.0.2.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
modprobe: can't change directory to '/lib/modules': No such file or directory
modprobe: can't change directory to '/lib/modules': No such file or directory
iptables v1.8.3 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
[#] ip link delete dev wg0

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  killed: false,
  code: 3,
  signal: null,
  cmd: 'wg-quick up wg0'
}
```

I'm running CentOS 8 and upgraded the kernel to 5.18.4, here is my output of `uname -r`:
```
$ uname -r
5.18.4-1.el8.elrepo.x86_64
```

```
$ modinfo wireguard
filename:       /lib/modules/5.18.4-1.el8.elrepo.x86_64/kernel/drivers/net/wireguard/wireguard.ko.xz
alias:          net-pf-16-proto-16-family-wireguard
alias:          rtnl-link-wireguard
version:        1.0.0
author:         Jason A. Donenfeld <Jason@zx2c4.com>
description:    WireGuard secure network tunnel
license:        GPL v2
srcversion:     746FF227790A0865A542034
depends:        udp_tunnel,curve25519-x86_64,libchacha20poly1305,ip6_udp_tunnel,libcurve25519-generic
retpoline:      Y
intree:         Y
name:           wireguard
vermagic:       5.18.4-1.el8.elrepo.x86_64 SMP preempt mod_unload modversions
```

**Comment by kpostekk** [comment]
I have a similar issue on fedora 36

`modprobe ip_tables && modprobe iptable-nat` solved my problems.

**Comment by kpostekk** [comment]
I know this issue is closed, but there is a better solution.

*modprobe is temporary but files are eternal*

```bash
echo 'iptable-nat' > /etc/modules-load.d/iptable-nat.conf
```

This should presist module loading.

**Comment by Tschuuuls** [comment]
I started the follwing kernel modules on my fedora 39 host to fix your iptables issues as well as this one:
`[#] iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;

iptables v1.8.3 (legacy): can't initialize iptables table `nat': Permission denied

Perhaps iptables or your kernel needs to be upgraded.`

`ip_tables
iptable_filter
iptable_nat
wireguard
xt_MASQUERADE`

thanks to @hasan4791 in https://github.com/containers/podman/issues/15120#issuecomment-1397571841_

**Comment by MisterAnderson91** [comment]
Thank you, after tearing my hair out on Fedora Server 40, I can confirm that the issue was the iptable-nat module not being loaded by default. The solution by kpostekk worked. Don't forget to reboot before running the container.

**Comment by Doomsdayrs** [comment]
Following the instructions to add those modules did not work for me. :(
