### ISSUE TITLE
wg-easy fails to start when on podman

### ISSUE THREAD

**Issue by killua-eu** [WeeJeWel/wg-easy#308]
Using the example and replacing `docker run` with `podman run` yields

```
2022-07-05T21:00:08.163Z Server Listening on http://0.0.0.0:51821
2022-07-05T21:00:08.164Z WireGuard Loading configuration...
2022-07-05T21:00:08.165Z WireGuard Configuration loaded.
2022-07-05T21:00:08.166Z WireGuard Config saving...
2022-07-05T21:00:08.167Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: Command failed: wg-quick up wg0
[#] 
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.8.0.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
iptables v1.8.3 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
[#] ip link delete dev wg0

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  killed: false,
  code: 3,
  signal: null,
  cmd: 'wg-quick up wg0'
}
```

Running with docker, everything works fine

**Comment by okkyhtf** [comment]
This is because the security defaults of podman. Podman drops NET_RAW capability as well which is required by Wireguard and by default not dropped in docker.

So you need to add this in addition to the ones for docker:
`--cap-add=NET_RAW` 

[1] https://github.com/containers/podman/issues/8784#issuecomment-749144728

**Comment by WeeJeWel** [comment]
Please propose a Wiki article to help others.

**Comment by Paragoumba** [comment]
I created [this wiki page](https://github.com/WeeJeWel/wg-easy/wiki/Using-WireGuard-Easy-with-Podman]

**Comment by WeeJeWel** [comment]
Very nice!
