### ISSUE TITLE
Error: Command failed: wg-quick up wg0

### ISSUE THREAD

**Issue by yangyuepeng** [WeeJeWel/wg-easy#33]
2021-06-11T05:03:41.232Z Server Listening on http://0.0.0.0:51821
2021-06-11T05:03:41.233Z WireGuard Loading configuration...
2021-06-11T05:03:41.239Z WireGuard Configuration loaded.
2021-06-11T05:03:41.240Z WireGuard Saving config...
2021-06-11T05:03:41.250Z WireGuard Config saved.
$ wg-quick up wg0
Error: Command failed: wg-quick up wg0
Warning: `/etc/wireguard/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
RTNETLINK answers: Not supported
Unable to access interface: Protocol not supported
[#] ip link delete dev wg0
Cannot find device "wg0"

    at ChildProcess.exithandler (child_process.js:319:12)
    at ChildProcess.emit (events.js:376:20)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'wg-quick up wg0'
}

**Comment by Murzik2142** [comment]
I was helped by installing packages on the centos 8 host system.
Source: https://www.wireguard.com/install/
![image](https://user-images.githubusercontent.com/5649160/123579155-c14b6a00-d7f0-11eb-91cf-fe6242ab197b.png)

**Comment by WeeJeWel** [comment]
Please make sure your host's kernel supports WireGuard.
