### ISSUE TITLE
Container not working on Raspberry Pi 4

### ISSUE THREAD

**Issue by ptzetaa** [WeeJeWel/wg-easy#546]
2023-05-09T07:20:36.502Z Server Listening on http://0.0.0.0:51821
2023-05-09T07:20:36.505Z WireGuard Loading configuration...
2023-05-09T07:20:36.508Z WireGuard Configuration loaded.
2023-05-09T07:20:36.509Z WireGuard Config saving...
2023-05-09T07:20:36.512Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at async /app/lib/WireGuard.js:63:9

It says "This usually means that your host's kernel does not support WireGuard!" but rpi kernel supports WireGuard so any clue?

**Comment by rgriffogoes** [comment]
Hey! Could you explain how did you fix this? I have a rpi 3 A+ showing the same issue.
